### ISSUE TITLE
This should be open source?

### ISSUE THREAD

**Issue by cliftonc** [tes/redux-plupload#1]

**Comment by rouanw** [comment]
`redux-plupload` is open source! Do we know anyone who can make a logo? Build is here on Travis: https://travis-ci.org/tes/redux-plupload. It's not in the public npmjs registry just yet.

@cliftonc can we use the tesglobal npmjs account credentials to configure Travis to automatically publish to the npmjs registry? (We'd create and encrypt an API key like suggested here: https://docs.travis-ci.com/user/deployment/npm .) Or would you prefer a manual release process like Bosco has?

**Comment by cliftonc** [comment]
I prefer the manual release process - gives us more control.

**Comment by rouanw** [comment]
`redux-plupload` is now available in the npm registry: https://www.npmjs.com/package/redux-plupload.
