### ISSUE TITLE
Built version at npm

### ISSUE THREAD

**Issue by 0on** [tes/redux-plupload#11]
Hi, I have a small problem with your package. After installation through npm there is no lib folder. So I have to run
`npm i && npm run build` in node_modules/redux-plupload
or use something like
`import reducer from 'redux-plupload/es6/reducer`.
May be it would be better to publish package after travis build?

**Comment by franferdez** [comment]
Same problem here.

**Comment by Pofigizm** [comment]
if you use
``` 
import reducer from 'redux-plupload/es6/reducer
```
you have to specify it in your webpack config
```
...
      {
        test: /\.js$/,
        use: [
          'babel-loader',
        ],
        exclude: /node_modules(?!\/redux-plupload\/es6)/,
      },
...
```

**Comment by cliftonc** [comment]
Thanks, we will get this sorted.

**Comment by rouanw** [comment]
@0on @franferdez @pofigizm sorry about the long wait but we've finally gotten around to sorting this 😸 

Would one of you please try `npm i redux-plupload@latest` and let me know whether the new version fixes your problem? The default include is now ES5 code, compatible with IE11+ ( [same as `redux`](https://github.com/reduxjs/redux/blob/1a1c7ac2a8768127d89bc866acce73340148bdc4/.babelrc.js#L9)).

**Comment by rouanw** [comment]
@0on @franferdez @pofigizm  I'm going to close this issue, but please let me know whether your issue has been resolved.
